import { GoogleGenAI, Type, ThinkingLevel } from "@google/genai";
import { addMinutes, isBefore } from "date-fns";

export interface ParsedReminder {
  title: string;
  description?: string;
  due_date: string; // Event Date and Time
  first_reminder_at: string; // First Reminder Date and Time
  urgency: "low" | "normal" | "high" | "critical";
  repeat_interval_minutes?: number; // Reminder gap
  repeat_count?: number;
  channels?: string[];
  isFallback: boolean;
}

export async function parseReminderWithAI(text: string, referenceTime: string, timezone: string): Promise<ParsedReminder> {
  const fallbackParse = (input: string): ParsedReminder => {
    const lower = input.toLowerCase();
    let title = input.replace(/remind me to /i, "").replace(/at .*/i, "").replace(/in .*/i, "").trim();
    let dueDate = addMinutes(new Date(referenceTime), 60);

    const inMinutesMatch = lower.match(/in (\d+) minutes?/);
    if (inMinutesMatch) {
      dueDate = addMinutes(new Date(referenceTime), parseInt(inMinutesMatch[1]));
    }

    const atTimeMatch = lower.match(/at (\d{1,2})(:(\d{2}))?\s*(am|pm)?/);
    if (atTimeMatch) {
      let hours = parseInt(atTimeMatch[1]);
      const mins = atTimeMatch[3] ? parseInt(atTimeMatch[3]) : 0;
      const ampm = atTimeMatch[4];
      if (ampm === 'pm' && hours < 12) hours += 12;
      if (ampm === 'am' && hours === 12) hours = 0;
      
      const d = new Date(referenceTime);
      d.setHours(hours, mins, 0, 0);
      if (isBefore(d, new Date(referenceTime))) {
        d.setDate(d.getDate() + 1);
      }
      dueDate = d;
    }

    return {
      title: title || "New Event",
      due_date: dueDate.toISOString(),
      first_reminder_at: addMinutes(dueDate, -15).toISOString(), // Default 15 mins before
      urgency: "normal",
      channels: ["push"],
      isFallback: true
    };
  };

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn("[AI Parse] GEMINI_API_KEY missing, using fallback");
    return fallbackParse(text);
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
      model: "gemini-3.1-pro-preview",
      contents: `Current User Local Time: ${referenceTime}\nTimezone: ${timezone}\nINPUT: "${text}"`,
      config: {
        systemInstruction: `You are an expert scheduling assistant. Parse the user's natural language event into a structured JSON object.
        
        REQUIREMENTS:
        1. Extract the core 'title' (Name of Event).
        2. Calculate 'due_date' (ISO 8601) for the actual event time.
        3. Calculate 'first_reminder_at' (ISO 8601). If not specified, default to 15 minutes before the event.
        4. Determine 'repeat_interval_minutes' (Reminder gap). If user says "every 5 mins", set to 5.
        5. Set 'repeat_count' to 999 if a gap is specified, as the user wants to be reminded until the task is complete.
        6. Determine 'urgency': "low", "normal", "high", or "critical".
        7. Suggest 'channels': array of "push", "sms", "whatsapp".
        
        If the input is vague, make reasonable assumptions based on common human behavior.`,
        thinkingConfig: { thinkingLevel: ThinkingLevel.HIGH },
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            title: { type: Type.STRING },
            description: { type: Type.STRING },
            due_date: { type: Type.STRING },
            first_reminder_at: { type: Type.STRING },
            urgency: { type: Type.STRING, enum: ["low", "normal", "high", "critical"] },
            repeat_interval_minutes: { type: Type.NUMBER },
            repeat_count: { type: Type.NUMBER },
            channels: { type: Type.ARRAY, items: { type: Type.STRING } }
          },
          required: ["title", "due_date", "first_reminder_at"]
        }
      }
    });

    const textResponse = response.text;
    if (!textResponse) throw new Error("Empty AI response");

    const parsed = JSON.parse(textResponse);
    if (isNaN(Date.parse(parsed.due_date))) throw new Error("Invalid date generated by AI");

    return { ...parsed, isFallback: false };
  } catch (error) {
    console.error("[AI Parse] Error, falling back:", error);
    return fallbackParse(text);
  }
}
